export {default as AddTask} from './AddTask'
export {default as TasksList} from './TasksList'
export {default as SingleTask} from './SingleTask'
export {default as Register} from './Register'
export {default as NavBar} from './NavBar'
export {default as Login} from './Login'